USE [master]
GO

/****** Object:  Database [NewDb]    Script Date: 04/08/2020 19:58:31 ******/
CREATE DATABASE [NewDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NewDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NewDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NewDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NewDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NewDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NewDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NewDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NewDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NewDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [NewDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NewDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NewDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NewDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NewDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NewDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NewDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NewDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NewDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NewDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NewDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NewDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NewDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NewDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NewDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NewDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NewDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NewDb] SET RECOVERY FULL 
GO

ALTER DATABASE [NewDb] SET  MULTI_USER 
GO

ALTER DATABASE [NewDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NewDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NewDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NewDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NewDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NewDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NewDb] SET  READ_WRITE 
GO

